#include "y.tab.h"
#include <stdio.h>
extern int yylex();
extern char *yytext;

int main()
{
int token;
  while((token = yylex())!=0){
    switch(token)
    {
      case AUTO : printf("<AUTO, %d, %s>\n",token,yytext);
        break;
      case BREAK : printf("<BREAK, %d, %s>\n",token,yytext);
        break;
      case CASE : printf("<CASE, %d, %s>\n",token,yytext);
        break;
      case CHAR : printf("<CHAR, %d, %s>\n",token,yytext);
        break;
      case CONST : printf("<CONST, %d, %s>\n",token,yytext);
        break;
      case CONTINUE : printf("<CONTINUE, %d, %s>\n",token,yytext);
        break;
      case DEFAULT : printf("<DEFAULT, %d, %s>\n",token,yytext);
        break;
      case DO : printf("<DO, %d, %s>\n",token,yytext);
        break;
      case DOUBLE : printf("<DOUBLE, %d, %s>\n",token,yytext);
        break;
      case ELSE : printf("<ELSE, %d, %s>\n",token,yytext);
        break;
      case ENUM : printf("<ENUM, %d, %s>\n",token,yytext);
        break;
      case EXTERN : printf("<EXTERN, %d, %s>\n",token,yytext);
        break;
      case FLOAT : printf("<FLOAT, %d, %s>\n",token,yytext);
        break;
      case FOR : printf("<FOR, %d, %s>\n",token,yytext);
        break;
      case GOTO : printf("<GOTO, %d, %s>\n",token,yytext);
        break;
      case IF : printf("<IF, %d, %s>\n",token,yytext);
        break;
      case INLINE : printf("<INLINE, %d, %s>\n",token,yytext);
        break;
      case INT : printf("<INT, %d, %s>\n",token,yytext);
        break;
      case LONG : printf("<LONG, %d, %s>\n",token,yytext);
        break;
      case REGISTER : printf("<REGISTER, %d, %s>\n",token,yytext);
        break;
      case RESTRICT : printf("<RESTRICT, %d, %s>\n",token,yytext);
        break;
      case RETURN : printf("<RETURN, %d, %s>\n",token,yytext);
        break;
      case SHORT : printf("<SHORT, %d, %s>\n",token,yytext);
        break;
      case SIGNED : printf("<SIGNED, %d, %s>\n",token,yytext);
        break;
      case SIZEOF : printf("<SIZEOF, %d, %s>\n",token,yytext);
        break;
      case STATIC : printf("<STATIC, %d, %s>\n",token,yytext);
        break;
      case STRUCT : printf("<STRUCT, %d, %s>\n",token,yytext);
        break;
      case SWITCH : printf("<SWITCH, %d, %s>\n",token,yytext);
        break;
      case TYPEDEF : printf("<TYPEDEF, %d, %s>\n",token,yytext);
        break;
      case UNION : printf("<UNION, %d, %s>\n",token,yytext);
        break;
      case UNSIGNED : printf("<UNSIGNED, %d, %s>\n",token,yytext);
        break;
      case VOID : printf("<VOID, %d, %s>\n",token,yytext);
        break;
      case VOLATILE : printf("<VOLATILE, %d, %s>\n",token,yytext);
        break;
      case WHILE : printf("<WHILE, %d, %s>\n",token,yytext);
        break;
      case BOOL : printf("<BOOL, %d, %s>\n",token,yytext);
        break;
      case COMPLEX : printf("<COMPLEX, %d, %s>\n",token,yytext);
        break;
      case IMAGINARY : printf("<IMAGINARY, %d, %s>\n",token,yytext);
        break;
      case ONELINE_COMMENT : printf("<ONELINE_COMMENT, %d, %s>\n",token,yytext);
        break;
      case MULTI_LINE_COMMENT :  printf("<MULTI_LINE_COMMENT, %d, %s>\n",token,yytext);
        break;
      case IDENTIFIER : printf("<IDENTIFIER, %d, %s>\n",token,yytext);
        break;
      case INTEGER_NO : printf("<INTEGER_NO, %d, %s>\n",token,yytext);
        break;
      case FLOAT_NO : printf("<FLOAT_NO, %d, %s>\n",token,yytext);
        break;
      case ENUMERATION_CONSTANT : printf("<ENUMERATION_CONSTANT, %d, %s>\n",token,yytext);
        break;
      case CHARACTER : printf("<CHARACTER, %d, %s>\n",token,yytext);
        break;
      case STRING : printf("<STRING, %d, %s>\n",token,yytext);
        break;
      case LEFT_SQUARE_BRACK : printf("<LEFT_SQUARE_BRACKET, %d, %s>\n",token,yytext);
        break;
      case RIGHT_SQUARE_BRACK : printf("<RIGHT_SQUARE_BRACKET, %d, %s>\n",token,yytext);
        break;
      case LEFT_ROUND_BRACK : printf("<LEFT_ROUND_BRACKET, %d, %s>\n",token,yytext);
        break;
      case RIGHT_ROUND_BRACK : printf("<RIGHT_ROUND_BRACKET, %d, %s>\n",token,yytext);
        break;
      case LEFT_CURLY_BRACK : printf("<LEFT_CURLY_BRACKET, %d, %s>\n",token,yytext);
        break;
    case RIGHT_CURLY_BRACK : printf("<RIGHT_CURLY_BRACKET, %d, %s>\n",token,yytext);
      break;
    case DOT : printf("<DOT, %d, %s>\n",token,yytext);
      break;
    case ARROW : printf("<ARROW, %d, %s>\n",token,yytext);
      break;
    case INCREM : printf("<INCREMENT, %d, %s>\n",token,yytext);
      break;
    case DECREM : printf("<DECREMENT, %d, %s>\n",token,yytext);
      break;
    case AMPEAND : printf("<AMPERSAND, %d, %s>\n",token,yytext);
      break;
    case MULTIPLICATION : printf("<MULTIPLICATION, %d, %s>\n",token,yytext);
      break;
    case ADDITION : printf("<ADDITION, %d, %s>\n",token,yytext);
      break;
    case SUBTRACTION : printf("<SUBTRACTION, %d, %s>\n",token,yytext);
      break;
    case TILDA : printf("<TILDA, %d, %s>\n",token,yytext);
      break;
    case NEGAT : printf("<NEGATION, %d, %s>\n",token,yytext);
      break;
    case FORWARD_SLA : printf("<FORWARD_SLASH, %d, %s>\n",token,yytext);
      break;
    case percent : printf("<PERCENTILE, %d, %s>\n",token,yytext);
      break;
    case LEFT_SHIFT : printf("<LEFT_SHIFT, %d, %s>\n",token,yytext);
      break;
    case RIGHT_SHIFT : printf("<RIGHT_SHIFT, %d, %s>\n",token,yytext);
      break;
    case LESS_THAN : printf("<LESS_THAN, %d, %s>\n",token,yytext);
      break;
    case GREATER_THAN : printf("<GREATER_THAN, %d, %s>\n",token,yytext);
      break;
    case LES_EQUAL : printf("<LESS_EQUAL, %d, %s>\n",token,yytext);
      break;
    case GREAT_EQUAL : printf("<GREATER_EQUAL, %d, %s>\n",token,yytext);
      break;
    case EQUAL_EQUAL : printf("<EQUAL_EQUAL, %d, %s>\n",token,yytext);
      break;
    case NOT_EQUAL : printf("<NOT_EQUAL, %d, %s>\n",token,yytext);
      break;
    case EXCLUSIVE_OR : printf("<EXCLUSIVE_OR, %d, %s>\n",token,yytext);
      break;
    case OR : printf("<OR, %d, %s>\n",token,yytext);
      break;
    case B_AND : printf("<BINARY_AND, %d, %s>\n",token,yytext);
      break;
    case B_OR : printf("<BINARY_OR, %d, %s>\n",token,yytext);
      break;
    case ELLIPSIS : printf("<ELLIPSIS, %d, %s>\n",token,yytext);
      break;
    case QUESTION : printf("<QUESTION_MARK, %d, %s>\n",token,yytext);
      break; 
    case COLON : printf("<COLON, %d, %s>\n",token,yytext);
      break; 
    case SEMI_COLON : printf("<SEMI_COLON, %d, %s>\n",token,yytext);
      break;
    case EQUAL : printf("<EQUAL, %d, %s>\n",token,yytext);
      break;
    case ST_EQUAL : printf("<STAR_EQUAL, %d, %s>\n",token,yytext);
      break;
    case SLASH_EQUAL : printf("<SLASH_EQUAL, %d, %s>\n",token,yytext);
      break;
    case percent_EQUAL : printf("<PERCENTILE_EQUAL, %d, %s>\n",token,yytext);
      break;
    case add_EQUAL : printf("<PLUS-EQUAL, %d, %s>\n",token,yytext);
      break;
    case MINUS_EQUAL : printf("<MINUS_EQUAL, %d, %s>\n", token,yytext);
      break;
    case LEFT_SHIFT_EQUAL : printf("<LEFT_SHIFT_EQUAL, %d, %s>\n",token,yytext);
      break;
    case RIGHT_SHIFT_EQUAL : printf("<RIGHT_SHIFT_EQUAL, %d, %s>\n",token,yytext);
      break;
    case AND_EQUAL : printf("<AND_EQUAL, %d, %s>\n",token,yytext);
      break;
    case X_EQUAL : printf("<XOR_=, %d, %s>\n",token,yytext);
      break;
    case OR_EQUAL : printf("<OR_EQUAL, %d, %s>\n",token,yytext);
      break;
    case COMMA : printf("<COMMA, %d, %s>\n",token,yytext);
      break;
    case HASH : printf("<HASH, %d, %s>\n",token,yytext);
      break;
    }
  }
}
